// https://api.unminable.com/v4/coin
// 2021-08-25 22:08:22
// Use a js module instead ajax

export const apiv4coin = {
  success: true,
  msg: 'Ok',
  data: [
    {
      symbol: '1INCH',
      network: 'ETH',
      token_standard: 'ERC20',
      name: '1inch',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 1,
      logo: 'https://www.unmineable.com/img/logos/1INCH.png',
    },
    {
      symbol: 'CHZ',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Chiliz',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 1,
      logo: 'https://www.unmineable.com/img/logos/CHZ.png',
    },
    {
      symbol: 'HOT',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Holo',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 1,
      logo: 'https://www.unmineable.com/img/logos/HOT.png',
    },
    {
      symbol: 'MATIC',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'MATIC (Polygon)',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 1,
      logo: 'https://www.unmineable.com/img/logos/MATIC.png',
    },
    {
      symbol: 'SHIB',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'SHIBA INU',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 1,
      logo: 'https://www.unmineable.com/img/logos/SHIB.png',
    },
    {
      symbol: 'SOL',
      network: 'SOL',
      token_standard: null,
      name: 'Solana',
      regex: '^[0-9a-zA-Z]{32,44}$',
      regex_memo: null,
      top: 1,
      logo: 'https://www.unmineable.com/img/logos/SOL.png',
    },
    {
      symbol: 'AAVE',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Aave',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/AAVE.png',
    },
    {
      symbol: 'ADA',
      network: 'ADA',
      token_standard: null,
      name: 'Cardano',
      regex: '^(([0-9A-Za-z]{57,59})|([0-9A-Za-z]{100,104}))$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ADA.png',
    },
    {
      symbol: 'ALGO',
      network: 'ALGO',
      token_standard: null,
      name: 'Algorand',
      regex: '^[A-Z0-9]{58,58}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ALGO.png',
    },
    {
      symbol: 'ATOM',
      network: 'ATOM',
      token_standard: null,
      name: 'Cosmos',
      regex: '^(cosmos1)[0-9a-z]{38}$',
      regex_memo: '^[0-9A-Za-z\\\\-_]{1,120}$',
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ATOM.png',
    },
    {
      symbol: 'BAND',
      network: 'BAND',
      token_standard: null,
      name: 'Band Protocol',
      regex: '^(band1)[0-9a-z]{38}$',
      regex_memo: '^[0-9A-Za-z\\\\-_]{1,120}$',
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BAND.png',
    },
    {
      symbol: 'BAT',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Basic Attention Token',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BAT.png',
    },
    {
      symbol: 'BCH',
      network: 'BCH',
      token_standard: null,
      name: 'Bitcoin Cash',
      regex: '^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$|^[0-9A-Za-z]{42,42}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BCH.png',
    },
    {
      symbol: 'BNB',
      network: 'BNB',
      token_standard: null,
      name: 'Binance Coin',
      regex: '^(bnb1)[0-9a-z]{38}$',
      regex_memo: '^[0-9A-Za-z\\\\-_]{1,120}$',
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BNB.png',
    },
    {
      symbol: 'BTC',
      network: 'BTC',
      token_standard: null,
      name: 'Bitcoin',
      regex: '^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$|^(bc1)[0-9A-Za-z]{39,59}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BTC.png',
    },
    {
      symbol: 'BTG',
      network: 'BTG',
      token_standard: null,
      name: 'Bitcoin Gold',
      regex: '^[AG][a-km-zA-HJ-NP-Z1-9]{25,34}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BTG.png',
    },
    {
      symbol: 'BTT',
      network: 'TRX',
      token_standard: 'TRC10',
      name: 'BitTorrent',
      regex: '^T[1-9A-HJ-NP-Za-km-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/BTT.png?v1',
    },
    {
      symbol: 'DASH',
      network: 'DASH',
      token_standard: null,
      name: 'Dash',
      regex: '^[X|7][0-9A-Za-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/DASH.png',
    },
    {
      symbol: 'DGB',
      network: 'DGB',
      token_standard: null,
      name: 'DigiByte',
      regex: '^[DS][a-km-zA-HJ-NP-Z1-9]{25,34}$|^(dgb1)[0-9A-Za-z]{39,59}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/DGB.png',
    },
    {
      symbol: 'DOGE',
      network: 'DOGE',
      token_standard: null,
      name: 'Dogecoin',
      regex: '^(D|A|9)[a-km-zA-HJ-NP-Z1-9]{33,34}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/DOGE.png',
    },
    {
      symbol: 'ENJ',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Enjin Coin',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ENJ.png',
    },
    {
      symbol: 'EOS',
      network: 'EOS',
      token_standard: null,
      name: 'EOS',
      regex: '^[1-5a-z\\.]{1,12}$',
      regex_memo: '^[0-9A-Za-z\\\\-_,]{1,120}$',
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/EOS.png',
    },
    {
      symbol: 'ETC',
      network: 'ETC',
      token_standard: null,
      name: 'Ethereum Classic',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ETC.png',
    },
    {
      symbol: 'ETH',
      network: 'ETH',
      token_standard: null,
      name: 'Ethereum',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ETH.png',
    },
    {
      symbol: 'FUN',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'FunFair',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/FUN.png',
    },
    {
      symbol: 'GAS',
      network: 'NEO',
      token_standard: null,
      name: 'GAS',
      regex: '^(A)[A-Za-z0-9]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/GAS.png',
    },
    {
      symbol: 'ICX',
      network: 'ICX',
      token_standard: null,
      name: 'ICON',
      regex: '^(hx)[A-Za-z0-9]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ICX.png',
    },
    {
      symbol: 'KLV',
      network: 'TRX',
      token_standard: 'TRC20',
      name: 'Klever',
      regex: '^T[1-9A-HJ-NP-Za-km-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/KLV.png?20211001',
    },
    {
      symbol: 'KNC',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'KyberNetwork',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/KNC.png',
    },
    {
      symbol: 'LINK',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'ChainLink',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/LINK.png',
    },
    {
      symbol: 'LSK',
      network: 'LSK',
      token_standard: null,
      name: 'Lisk',
      regex: '^[0-9]{12,22}[L]$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/LSK.png',
    },
    {
      symbol: 'LTC',
      network: 'LTC',
      token_standard: null,
      name: 'Litecoin',
      regex: '^(L|M|3)[A-Za-z0-9]{33}$|^(ltc1)[0-9A-Za-z]{39}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/LTC.png',
    },
    {
      symbol: 'MANA',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Decentraland',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/MANA.png',
    },
    {
      symbol: 'MTL',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Metal',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/MTL.png',
    },
    {
      symbol: 'NANO',
      network: 'NANO',
      token_standard: null,
      name: 'NANO',
      regex: '^(xrb_|nano_)[13456789abcdefghijkmnopqrstuwxyz]{60}',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/NANO.png',
    },
    {
      symbol: 'NEO',
      network: 'NEO',
      token_standard: null,
      name: 'NEO',
      regex: '^(A)[A-Za-z0-9]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/NEO.png',
    },
    {
      symbol: 'QTUM',
      network: 'QTUM',
      token_standard: null,
      name: 'Qtum',
      regex: '^[Q|M][A-Za-z0-9]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/QTUM.png',
    },
    {
      symbol: 'REP',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Augur',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/REP.png',
    },
    {
      symbol: 'RSR',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Reserve Rights',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/RSR.png',
    },
    {
      symbol: 'RVN',
      network: 'RVN',
      token_standard: null,
      name: 'Ravencoin',
      regex: '^[Rr]{1}[A-Za-z0-9]{33,34}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/RVN.png',
    },
    {
      symbol: 'SC',
      network: 'SC',
      token_standard: null,
      name: 'Siacoin',
      regex: '^[A-Za-z0-9]{76}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/SC.png',
    },
    {
      symbol: 'SKY',
      network: 'SKY',
      token_standard: null,
      name: 'Skycoin',
      regex: '^[0-9A-Za-z]{26,35}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/SKY.png',
    },
    {
      symbol: 'SUSHI',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Sushi',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/SUSHI.png',
    },
    {
      symbol: 'TRX',
      network: 'TRX',
      token_standard: null,
      name: 'TRON',
      regex: '^T[1-9A-HJ-NP-Za-km-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/TRX.png',
    },
    {
      symbol: 'UNI',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Uniswap',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/UNI.png',
    },
    {
      symbol: 'USDT',
      network: 'TRX',
      token_standard: 'TRC20',
      name: 'TetherUS',
      regex: '^T[1-9A-HJ-NP-Za-km-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/USDT.png',
    },
    {
      symbol: 'VET',
      network: 'VET',
      token_standard: null,
      name: 'VeChain',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/VET.png',
    },
    {
      symbol: 'VIA',
      network: 'VIA',
      token_standard: null,
      name: 'Viacoin',
      regex:
        '((V|E)[A-Za-z0-9]{33})|(via1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{39})',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/VIA.png',
    },
    {
      symbol: 'WAVES',
      network: 'WAVES',
      token_standard: null,
      name: 'Waves',
      regex: '^(3P)[0-9A-Za-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/WAVES.png',
    },
    {
      symbol: 'WBTC',
      network: 'ETH',
      token_standard: 'EC20',
      name: 'Wrapped Bitcoin',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/WBTC.png',
    },
    {
      symbol: 'WIN',
      network: 'TRX',
      token_standard: 'TRC20',
      name: 'WINk',
      regex: '^T[1-9A-HJ-NP-Za-km-z]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/WIN.png?20210406',
    },
    {
      symbol: 'XLM',
      network: 'XLM',
      token_standard: null,
      name: 'Stellar Lumens',
      regex: '^G[A-D]{1}[A-Z2-7]{54}$',
      regex_memo: '^[0-9A-Za-z]{1,28}$',
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/XLM.png',
    },
    {
      symbol: 'XMR',
      network: 'XMR',
      token_standard: null,
      name: 'Monero',
      regex: '^[48][a-zA-Z|\\d]{94}([a-zA-Z|\\d]{11})?$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/XMR.png',
    },
    {
      symbol: 'XRP',
      network: 'XRP',
      token_standard: null,
      name: 'Ripple',
      regex: '^r[1-9A-HJ-NP-Za-km-z]{25,34}$',
      regex_memo: '^((?!0)[0-9]{1,19})$',
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/XRP.png',
    },
    {
      symbol: 'XTZ',
      network: 'XTZ',
      token_standard: null,
      name: 'Tezos',
      regex: '^(tz[1,2,3]|KT1)[a-zA-Z0-9]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/XTZ.png',
    },
    {
      symbol: 'XVG',
      network: 'XVG',
      token_standard: null,
      name: 'Verge',
      regex: '^(D)[A-Za-z0-9]{33}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/XVG.png',
    },
    {
      symbol: 'YFI',
      network: 'ETH',
      token_standard: 'ERC20',
      name: 'Yearn.finance',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/YFI.png',
    },
    {
      symbol: 'ZEC',
      network: 'ZEC',
      token_standard: null,
      name: 'Zcash',
      regex: '^(t)[A-Za-z0-9]{34}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ZEC.png',
    },
    {
      symbol: 'ZIL',
      network: 'ZIL',
      token_standard: null,
      name: 'Zilliqa',
      regex: 'zil1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{38}',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ZIL.png',
    },
    {
      symbol: 'ZRX',
      network: 'ETH',
      token_standard: 'ERC20',
      name: '0x',
      regex: '^(0x)[0-9A-Fa-f]{40}$',
      regex_memo: null,
      top: 0,
      logo: 'https://www.unmineable.com/img/logos/ZRX.png',
    },
  ],
}
